FROM golang:1.25-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /goq-api ./cmd/api

FROM alpine:3.20
COPY --from=build /goq-api /goq-api
EXPOSE 8080
ENTRYPOINT ["/goq-api"]